import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import LoginChecker from "./LoginChecker";

export const metadata: Metadata = {
  title: "Application Tracking System",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <StoreProvider>
          <LoginChecker>
            {children}
          </LoginChecker>
        </StoreProvider>
      </body>
    </html>
  );
}
